version: "4.16"

services:
  database:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - .:/usrs/app

volumes:
  pgdata:
    driver: local
